name: 'PYCI SSH Remote Commands'
description: 'PYCI Executing remote ssh commands'
author: 'Zahl Lau'
inputs:
  host:
    description: 'scp remote host e.g. 1.2.3.4:22 or 1.2.3.4:22,5.6.7.8:234'
  username:
    description: 'login username'
  password:
    description: 'login password'
  key:
    description: 'ssh private key'
  proxy:
    description: 'only support socks5 proxy e.g. user:password@host:port'
  script:
    description: 'Commands to be executed.'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'yellow'
